import 'package:flutter/cupertino.dart';
import 'package:rflutter_alert/rflutter_alert.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class PaperBrain {
  BuildContext _context;
  int _paperIndex = 0;

  List<String> _paperTitles = [
    'Interventions for improving upper limb function after stroke',
    'Differences in myoelectric and body-powered upper-limb prostheses: Systematic literature review',
    'Rehabilitation methods for reducing shoulder subluxation in post-stroke hemiparesis: a systematic review',
    'Exoskeleton and End-Effector Robots for Upper and Lower Limbs Rehabilitation: Narrative Review',
    'Intensive virtual reality and robotic based upper limb training compared to usual care, and associated cortical reorganization, in the acute and early sub-acute periods post-stroke: a feasibility study',
    'Learning of Artificial Sensation Through Long-Term Home Use of a Sensory-Enabled Prosthesis',
    'Neurotechnology-aided interventions for upper limb motor rehabilitation in severe chronic stroke',
    'Upper limb robotics applied to neurorehabilitation: An overview of clinical practice',
    'A review of invasive and non-invasive sensory feedback in upper limb prostheses',
    'Brain-Machine Interfaces: From Basic Science to Neuroprostheses and Neurorehabilitation',
    'Restoring Motor Functions After Stroke: Multiple Approaches and Opportunities',
    'Upper limb cortical maps in amputees with targeted muscle and sensory reinnervation',
    'Feasibility of an Electromyography-Triggered Hand Robot for People After Chronic Stroke',
    'Restoration of motor control and proprioceptive and cutaneous sensation in humans with prior upper-limb amputation via multiple Utah Slanted Electrode Arrays (USEAs) implanted in residual peripheral arm nerves',
    'High-performance neuroprosthetic control by an individual with tetraplegia',
    'Mental practice for upper limb rehabilitation after stroke: a systematic review and meta-analysis',
    'Transcutaneous Vagus Nerve Stimulation Combined with Robotic Rehabilitation Improves Upper Limb Function after Stroke',
    'Clinical improvement with intensive robot-assisted arm training in chronic stroke is unchanged by supplementary tDCS',
    'An Orthopaedic Robotic-Assisted Rehabilitation Method of the Forearm in Virtual Reality Physiotherapy',
    'Evolution of Neuroprosthetic Approaches to Restoration of Upper Extremity Function in Spinal Cord Injury',
    'Upbeat: Augmented Reality-Guided Dancing for Prosthetic Rehabilitation of Upper Limb Amputees',
    'Motor learning with the PNF-concept, an alternative to constrained induced movement therapy in a patient after a stroke; a case report',
    'Effectiveness of a single session of dual-transcranial direct current stimulation in combination with upper limb robotic-assisted rehabilitation in chronic stroke patients: a randomized, double-blind, cross-over study',
    'Early intervention to improve hand function in hemiplegic cerebral palsy',
    'Adding vibrotactile feedback to a myoelectric-controlled hand improves performance when online visual feedback is disturbed',
    'Self-directed therapy programmes for arm rehabilitation after stroke: a systematic review',
    'Upper limb robotic rehabilitation for chronic stroke survivors: a single-group preliminary study',
    'Brain-machine interface of upper limb recovery in stroke patients rehabilitation: A systematic review',
    'Effect of vibration characteristics and vibror arrangement on the tactile perception of the upper arm in healthy subjects and upper limb amputees',
    'Phantom motor execution as a treatment for phantom limb pain: protocol of an international, double-blind, randomised controlled clinical trial',
    'Immersive Virtual Reality Therapy with Myoelectric Control for Treatment-resistant Phantom Limb Pain: Case Report',
    'Outcomes, Challenges, and Pitfalls after Targeted Muscle Reinnervation in High-Level Amputees: Is It Worth the Effort?',
    'Evaluation of Optimal Vibrotactile Feedback for Force-Controlled Upper Limb Myoelectric Prostheses',
    'Recovery of Proprioception in the Upper Extremity by Robotic Mirror Therapy: a Clinical Pilot Study for Proof of Concept',
    'Comparison of vibrotactile and joint-torque feedback in a myoelectric upper-limb prosthesis',
    'Reflections on the present and future of upper limb prostheses',
    'Myoelectric control with abstract decoders',
    'Methods for an Investigation of Neurophysiological and Kinematic Predictors of Response to Upper Extremity Repetitive Task Practice in Chronic Stroke',
    'Who May Benefit From Armeo Power Treatment? A Neurophysiological Approach to Predict Neurorehabilitation Outcomes',
    'A robot hand testbed designed for enhancing embodiment and functional neurorehabilitation of body schema in subjects with upper limb impairment or loss',
    'Robot-Aided Upper-limb Proprioceptive Training in Three-Dimensional Space',
    'Spatio-temporal profile of brain activity during gentle touch investigated with magnetoencephalography',
    'Effect of a mixed reality-based intervention on arm, hand, and finger function on chronic stroke',
    'Audible Feedback Improves Internal Model Strength and Performance of Myoelectric Prosthesis Control',
    'Evaluation of Performance-Based Outcome Measures for the Upper Limb: A Comprehensive Narrative Review',
    'Upper-Limb Robotic Exoskeletons for Neurorehabilitation: A Review on Control Strategies',
    'The Association Between Reorganization of Bilateral M1 Topography and Function in Response to Early Intensive Hand Focused Upper Limb Rehabilitation Following Stroke Is Dependent on Ipsilesional Corticospinal Tract Integrity',
    'The clinical relevance of advanced artificial feedback in the control of a multi-functional myoelectric prosthesis',
    'Motor imagery classification of upper limb movements based on spectral domain features of EEG patterns',
    'Tremor Control Devices for Essential Tremor: A Systematic Literature Review',
    'Robotic-assisted rehabilitation of the upper limb after acute stroke',
    'Providing a sense of touch to prosthetic hands',
    'Limb Position Tolerant Pattern Recognition for Myoelectric Prosthesis Control with Adaptive Sparse Representations From Extreme Learning',
    'Neuromimetic Event-Based Detection for Closed-Loop Tactile Feedback Control of Upper Limb Prostheses',
    'Skin Stretch Haptic Feedback to Convey Closure Information in Anthropomorphic, Under-Actuated Upper Limb Soft Prostheses',
    'Sensory feedback by peripheral nerve stimulation improves task performance in individuals with upper limb loss using a myoelectric prosthesis',
    'SVM-Based Classification of sEMG Signals for Upper-Limb Self-Rehabilitation Training',
    'Literature Review on Needs of Upper Limb Prosthesis Users',
    'Four Extremity Amputation and Bionic Prosthesis Supply after Disseminated Intravascular Coagulation: A Follow-Up on Functionality and Quality of Life after Bionic Prosthesis Supply',
    'Sensory feedback for upper limb prostheses',
    'Myoelectric signal processing for control of powered limb prostheses',
    'Vibrotactile grasping force and hand aperture feedback for myoelectric forearm prosthesis users',
    'The benefits of sensation on the experience of a hand: A qualitative case series',
    'Motor unit drive: a neural interface for real-time upper limb prosthetic control',
    'Computerised mirror therapy with Augmented Reflection Technology for early stroke rehabilitation: clinical feasibility and integration as an adjunct therapy',
    'Myocontrol is closed-loop control: incidental feedback is sufficient for scaling the prosthesis force in routine grasping',
    'Non-Invasive, Temporally Discrete Feedback of Object Contact and Release Improves Grasp Control of Closed-Loop Myoelectric Transradial Prostheses',
    'Discrimination and Recognition of Phantom Finger Sensation Through Transcutaneous Electrical Nerve Stimulation',
    'Electroencephalographic markers of robot-aided therapy in stroke patients for the evaluation of upper limb rehabilitation',
    'Artificial tactile and proprioceptive feedback improves performance and confidence on object identification tasks',
    'Restoring tactile and proprioceptive sensation through a brain interface',
    'Vestibular feedback maintains reaching accuracy during body movement',
    'Quantification of upper limb position sense using an exoskeleton and a virtual reality display',
    'A review of methods for achieving upper limb movement following spinal cord injury through hybrid muscle stimulation and robotic assistance',
    'Upper extremity myoelectric prosthetics',
    'Designing Feedback Controllers for Human-Prosthetic Systems Using H âˆž Model Matching',
    'Recapitulating flesh with silicon and steel: advancements in upper extremity robotic prosthetics',
    'Real-time robustness evaluation of regression based myoelectric control against arm position change and donning/doffing',
    'Feasibility of gestural feedback treatment for upper extremity movement in children with cerebral palsy',
    'Giuliano Vanghetti and the innovation of "cineplastic operations"',
    'Brain network involved in visual processing of movement stimuli used in upper limb robotic training: an fMRI study',
    'When Less Is More - Discrete Tactile Feedback Dominates Continuous Audio Biofeedback in the Integrated Percept While Controlling a Myoelectric Prosthetic Hand',
    'The Arm Movement Detection (AMD) test: a fast robotic test of proprioceptive acuity in the arm',
    'Sensory feedback in upper limb prosthetics',
    'Developing Non-Somatotopic Phantom Finger Sensation to Comparable Levels of Somatotopic Sensation through User Training With Electrotactile Stimulation',
    'A Novel Flexible Sensor for Muscle Shape Change Monitoring in Limb Motion Recognition',
    'A qualitative study exploring views and experiences of people with stroke undergoing transcranial direct current stimulation and upper limb robot therapy',
    'Improving the functionality, robustness, and adaptability of myoelectric control for dexterous motion restoration',
    'Robotic therapy provides a stimulus for upper limb motor recovery after stroke that is complementary to and distinct from conventional therapy',
    'Literature Review on the Effects of tDCS Coupled with Robotic Therapy in Post Stroke Upper Limb Rehabilitation',
    'Investigation of Fatigability during Repetitive Robot-Mediated Arm Training in People with Multiple Sclerosis',
    'Electromyography Assessment of the Assistance Provided by an Upper-Limb Exoskeleton in Maintenance Tasks',
    'Assessment of Robot Interventions in a Task-based Rehabilitation: a case study',
    'Objective Assessment of Spasticity With a Method Based on a Human Upper Limb Model',
    'Closed-Loop Continuous Hand Control via Chronic Recording of Regenerative Peripheral Nerve Interfaces',
    'Fall Prevalence and Contributors to the Likelihood of Falling in Persons With Upper Limb Loss',
    'Data Driven Spatial Filtering Can Enhance Abstract Myoelectric Control in Amputees',
    'The effects of upper limb posture and a sub-maximal gripping task on corticospinal excitability to muscles of the forearm',
    'Impact of early applied upper limb stimulation: the EXPLICIT-stroke programme design',
    'Controlling a multi-degree of freedom upper limb prosthesis using foot controls: user experience',
    'Decoding Upper Limb Movement Attempt From EEG Measurements of the Contralesional Motor Cortex in Chronic Stroke Patients',
    'Resolving the adverse impact of mobility on myoelectric pattern recognition in upper-limb multifunctional prostheses',
    'Preliminary Evaluation of Disturbance Torque Estimation Approaches for Lower-limb Robotic Rehabilitation',
    'The quest for the bionic arm',
    'Feedforward model based arm weight compensation with the rehabilitation robot ARMin',
    'A Control Architecture for Grasp Strength Regulation in Myocontrolled Robotic Hands Using Vibrotactile Feedback: Preliminary Results',
    'Development of subliminal persuasion system to improve the upper limb posture in laparoscopic training: a preliminary study',
    'AsTeRICS',
    'Beyond therapists: Technology-aided physical MS rehabilitation delivery',
    'Neural coupling between upper and lower limbs during recumbent stepping',
    'Somatotopical feedback versus non-somatotopical feedback for phantom digit sensation on amputees using electrotactile stimulation',
    'Feasibility of error-based electrotactile and auditive feedback in prosthetic walking',
    'Robustness and Reliability of Synergy-Based Myocontrol of a Multiple Degree of Freedom Robotic Arm',
    'Electrotactile Feedback with Spatial and Mixed Coding for Object Identification and Closed-loop Control of Grasping Force in Myoelectric Prostheses',
    'Adaptive hybrid robotic system for rehabilitation of reaching movement after a brain injury: a usability study',
    'Biological and bionic hands: natural neural coding and artificial perception',
    'Brain state-dependent robotic reaching movement with a multi-joint arm exoskeleton: combining brain-machine interfacing and robotic rehabilitation',
    'Detection of movement onset using EMG signals for upper-limb exoskeletons in reaching tasks',
    'Reach and grasp by people with tetraplegia using a neurally controlled robotic arm',
    'Composite forearm free fillet flaps to preserve stump length following traumatic amputations of the upper extremity',
    'Bone Conduction as Sensory Feedback Interface: A Preliminary Study',
    'Fascicular Topography of the Human Median Nerve for Neuroprosthetic Surgery',
    'Visuomotor behaviors and performance in a dual-task paradigm with and without vibrotactile feedback when using a myoelectric controlled hand',
    'A motion-classification strategy based on sEMG-EEG signal combination for upper-limb amputees',
    'Use of lateral upper arm free flaps for soft-tissue reconstruction of the contracted eye socket',
    'The efficacy of SMART Arm training early after stroke for stroke survivors with severe upper limb disability: a protocol for a randomised controlled trial',
    'Role of Muscle Synergies in Real-Time Classification of Upper Limb Motions using Extreme Learning Machines',
    'Psychometric characterization of incidental feedback sources during grasping with a hand prosthesis',
    'Learning in a virtual environment using haptic systems for movement re-education: can this medium be used for remodeling other behaviors and actions?',
    'Evaluating the Effectiveness and Safety of the Electroencephalogram-Based Brain-Machine Interface Rehabilitation System for Patients With Severe Hemiparetic Stroke: Protocol for a Randomized Controlled Trial (BEST-BRAIN Trial)',
    'Key considerations in designing a somatosensory neuroprosthesis',
    'A composite robotic-based measure of upper limb proprioception',
    'Performance-based robotic assistance during rhythmic arm exercises',
    'Blending of brain-machine interface and vision-guided autonomous robotics improves neuroprosthetic arm performance during grasping',
    'A neural tracking and motor control approach to improve rehabilitation of upper limb movements',
    'Compensation or Restoration: Closed-Loop Feedback of Movement Quality for Assisted Reach-to-Grasp Exercises with a Multi-Joint Arm Exoskeleton',
    'Electrical stimulation and iterative learning control for functional recovery in the upper limb post-stroke',
    'Combining Robotic Training and Non-Invasive Brain Stimulation in Severe Upper Limb-Impaired Chronic Stroke Patients',
    'Bimanual elbow robotic orthoses: preliminary investigations on an impairment force-feedback rehabilitation method',
    'Satisfaction and perceptions of long-term manual wheelchair users with a spinal cord injury upon completion of a locomotor training program with an overground robotic exoskeleton',
    'Design, control, and sensory feedback of externally powered hand prostheses: a literature review',
    'Training-induced changes in the pattern of triceps to biceps activation during reaching tasks after chronic and severe stroke',
    'Hybrid Neuroprosthesis for the Upper Limb: Combining Brain-Controlled Neuromuscular Stimulation with a Multi-Joint Arm Exoskeleton',
    'A Greedy Assist-as-Needed Controller for Upper Limb Rehabilitation',
    'Evaluation of upper limb sense of position in healthy individuals and patients after stroke',
    'Exploring Self-Paced Embodiable Neurofeedback for Post-stroke Motor Rehabilitation',
    'A regenerative peripheral nerve interface allows real-time control of an artificial hand in upper limb amputees',
    'Planar conformity of movements in 3D reaching tasks for persons with Multiple Sclerosis',
    'Proprioceptive Based Training for stroke recovery. Proposal of new treatment modality for rehabilitation of upper limb in neurological diseases',
    'Home Use of a Neural-connected Sensory Prosthesis Provides the Functional and Psychosocial Experience of Having a Hand Again',
    'A low-cost, wearable sEMG sensor for upper limb prosthetic application',
    'New horizons for robot-assisted therapy in pediatrics',
    'Corticospinal excitability as a predictor of functional gains at the affected upper limb following robotic training in chronic stroke survivors',
    'Quantification of task-dependent cortical activation evoked by robotic continuous wrist joint manipulation in chronic hemiparetic stroke',
    'Hard-wired Epimysial Recordings from Normal and Reinnervated Muscle Using a Bone-anchored Device',
    'Humans can integrate feedback of discrete events in their sensorimotor control of a robotic hand',
    'Influence of complementing a robotic upper limb rehabilitation system with video games on the engagement of the participants: a study focusing on muscle activities',
    'Rehabilitation of gait after stroke: a review towards a top-down approach',
    'Interventions to promote upper limb recovery in stroke survivors with severe paresis: a systematic review',
    'Integration of Forearm sEMG Signals with IMU Sensors for Trajectory Planning and Control of Assistive Robotic Arm',
    'Priorities for the design and control of upper limb prostheses: A focus group study',
    'Improving Fine Control of Grasping Force during Hand-Object Interactions for a Soft Synergy-Inspired Myoelectric Prosthetic Hand',
    'Interventions for improving coordination of reach to grasp following stroke: a systematic review',
    'Cortical Decoding of Individual Finger Group Motions Using ReFIT Kalman Filter',
    'Advantages of externally powered prosthesis with feedback system using pseudo-cineplasty',
    'Biomimetic Intraneural Sensory Feedback Enhances Sensation Naturalness, Tactile Sensitivity, and Manual Dexterity in a Bidirectional Prosthesis',
    'Visual vs vibrotactile feedback for posture assessment during upper-limb robot-aided rehabilitation',
    'Acquired limb deficiencies. 3. Prosthetic components, prescriptions, and indications',
    'Visuotactile synchrony of stimulation-induced sensation and natural somatosensation',
    'Electroencephalographic Changes of Brain Oscillatory Activity After Upper Limb Somatic Sensation Training in a Patient With Somatosensory Deficit After Stroke',
    'Applications of sensory feedback in motorized upper extremity prosthesis: a review',
    'Selectivity and Longevity of Peripheral-Nerve and Machine Interfaces: A Review',
    'Differential Activation of Biceps Brachii Muscle Compartments for Human-Machine Interfacing',
    'Exploiting the Intertemporal Structure of the Upper-Limb sEMG: Comparisons between an LSTM Network and Cross-Sectional Myoelectric Pattern Recognition Methods',
    'Systematic changes in position sense accompany normal aging across adulthood',
    'Real-time upper limb motion estimation from surface electromyography and joint angular velocities using an artificial neural network for human-machine cooperation',
    'The impact of the stimulation frequency on closed-loop control with electrotactile feedback',
    'Strategies for providing upper extremity amputees with tactile and hand position feedback--moving closer to the bionic arm',
    'Descending corticospinal control of intersegmental dynamics',
    'Expanding stroke telerehabilitation services to rural veterans: a qualitative study on patient experiences using the robotic stroke therapy delivery and monitoring system program',
    'Long-term decoding of movement force and direction with a wireless myoelectric implant',
    'Design of continuous EMG classification approaches towards the control of a robotic exoskeleton in reaching movements',
    'Technology-assisted training of arm-hand skills in stroke: concepts on reacquisition of motor control and therapist guidelines for rehabilitation technology design',
    'Classification Scheme for Arm Motor Imagery',
    'Elicitation of usability-related Requirements for Upper-Limb Rehabilitation Systems',
    'Decoding Lower Limb Muscle Activity and Kinematics from Cortical Neural Spike Trains during Monkey Performing Stand and Squat Movements',
    'Myoelectrically controlled wrist robot for stroke rehabilitation',
    'On the effect of muscular cocontraction on the 3-D human arm impedance',
    'Differentiated Effects of Robot Hand Training With and Without Neural Guidance on Neuroplasticity Patterns in Chronic Stroke',
    'Prediction of muscle activity during loaded movements of the upper limb',
    'Touch and Hearing Mediate Osseoperception',
    'Investigation of goal change to optimize upper-extremity motor performance in a robotic environment',
    'Myoelectric Computer Interface Training for Reducing Co-Activation and Enhancing Arm Movement in Chronic Stroke Survivors: A Randomized Trial',
    'The extraction of neural information from the surface EMG for the control of upper-limb prostheses: emerging avenues and challenges',
    'Brain-Machine Interface-Driven Post-Stroke Upper-Limb Functional Recovery Correlates With Beta-Band Mediated Cortical Networks',
    'A preliminary study for quantitative assessment of upper limb proprioception',
    'Surface EMG signals in very late-stage of Duchenne muscular dystrophy: a case study',
    'Adaptive Windowing Framework for Surface Electromyogram-Based Pattern Recognition System for Transradial Amputees',
    '["Bionic" arm prostheses. State of the art in research and development]',
    'Variable impact of tizanidine on the medium latency reflex of upper and lower limbs',
    'Reward and punishment enhance motor adaptation in stroke',
    'A haptic-robotic platform for upper-limb reaching stroke therapy: preliminary design and evaluation results',
    'A versatile robotic platform for the design of natural, three-dimensional reaching and grasping tasks in monkeys',
    'Humans can integrate force feedback to toes in their sensorimotor control of a robotic hand',
    'An Alternative Myoelectric Pattern Recognition Approach for the Control of Hand Prostheses: A Case Study of Use in Daily Life by a Dysmelia Subject',
    'A randomized controlled trial of gravity-supported, computer-enhanced arm exercise for individuals with severe hemiparesis',
    'Real-time classification of shoulder girdle motions for multifunctional prosthetic hand control: A preliminary study',
    'Interventions for improving coordination of reach to grasp following stroke: a systematic review',
    'SITAR: a system for independent task-oriented assessment and rehabilitation',
    'An augmented reality system for upper-limb post-stroke motor rehabilitation: a feasibility study',
    'A wearable skin stretch haptic feedback device: Towards improving balance control in lower limb amputees',
    'Employing the International Classification of Functioning, Disability and Health framework to capture user feedback in the design and testing stage of development of home-based arm rehabilitation technology',
    'Intuitive, online, simultaneous, and proportional myoelectric control over two degrees-of-freedom in upper limb amputees',
    'Effect of task-related continuous auditory feedback during learning of tracking motion exercises',
    'The SmartHand transradial prosthesis',
    'Neural correlates of the rubber hand illusion in amputees: a report of two cases',
    'Predictors and brain connectivity changes associated with arm motor function improvement from intensive practice in chronic stroke',
    'Feature Extraction of Shoulder Joint\'s Voluntary Flexion-Extension Movement Based on Electroencephalography Signals for Power Assistance',
    'Proprioceptive assessment in clinical settings: Evaluation of joint position sense in upper limb post-stroke using a robotic manipulator',
    'An Insulated Flexible Sensor for Stable Electromyography Detection: Applicationto Prosthesis Control',
    'Restoring the sense of touch with a prosthetic hand through a brain interface',
    'A myoelectric-controlled virtual hand for the assessment and treatment of phantom limb pain in trans-radial upper extremity amputees: a research protocol',
    'Sensory information from a slipping object elicits a rapid and automatic shoulder response',
    'PlayBionic: Game-Based Interventions to Encourage Patient Engagement and Performance in Prosthetic Motor Rehabilitation',
    'A fully implanted intramuscular bipolar myoelectric signal recording electrode',
    'Tactile Feedback in Closed-Loop Control of Myoelectric Hand Grasping: Conveying Information of Multiple Sensors Simultaneously via a Single Feedback Channel',
    'Behavioral demonstration of a somatosensory neuroprosthesis',
    'Detecting intention to grasp during reaching movements from EEG',
    'A robotic model to investigate human motor control',
    'A Modular Transradial Bypass Socket for Surface Myoelectric Prosthetic Control in Non-Amputees',
    'Using Virtual Reality to Transfer Motor Skill Knowledge from One Hand to Another',
    'Propriospinal transmission of part of the corticospinal excitation in humans',
    'Using Functional Electrical Stimulation Mediated by Iterative Learning Control and Robotics to Improve Arm Movement for People With Multiple Sclerosis',
    'A training platform for many-dimensional prosthetic devices using a virtual reality environment',
    'Quantitative EEG for Predicting Upper Limb Motor Recovery in Chronic Stroke Robot-Assisted Rehabilitation',
    'A biologically inspired neural network controller for ballistic arm movements',
    'Robotic techniques for upper limb evaluation and rehabilitation of stroke patients',
    '[Smart Rehab: App-based rehabilitation training for upper extremity amputees - Case Report]',
    'Characterization of In-Body to On-Body Wireless Radio Frequency Link for Upper Limb Prostheses',
    'Targeted muscle reinnervation and advanced prosthetic arms',
    'Prosthetic design directives: Low-cost hands within reach',
    'Examination of force discrimination in human upper limb amputees with reinnervated limb sensation following peripheral nerve transfer',
    'Development of Activity-Related Muscle Fatigue during Robot-Mediated Upper Limb Rehabilitation Training in Persons with Multiple Sclerosis: A Pilot Trial',
    'Closed-Loop Control of Myoelectric Prostheses With Electrotactile Feedback: Influence of Stimulation Artifact and Blanking',
    'Surgeon\'s muscle load during robotic-assisted laparoscopy performed with a regular office chair and the preferred of two ergonomic chairs: A pilot study',
    'Identifying the effects of using integrated haptic feedback for gait rehabilitation of stroke patients',
    'Referral of sensation to an advanced humanoid robotic hand prosthesis',
    'HD-sEMG-based research on activation heterogeneity of skeletal muscles and the joint force estimation during elbow flexion',
    'Design and Characterization of a Robotic Device for the Assessment of Hand Proprioceptive, Motor, and Sensorimotor Impairments',
    'Myoelectric signal from below the level of spinal cord injury as a command source for an implanted upper extremity neuroprosthesis - a case report',
    'Enhanced visual feedback for slip prevention with a prosthetic hand',
    'Construction of efficacious gait and upper limb functional interventions based on brain plasticity evidence and model-based measures for stroke patients',
    'The artificial substitution of missing hands with myoelectrical prostheses',
    'The arm motion detection (AMD) test',
    'A cosmetic prosthetic digit with bioinspired embedded touch feedback',
    'Development of quantitative and sensitive assessments of physiological and functional outcome during recovery from spinal cord injury: a clinical initiative',
    'Sensory synergy as environmental input integration',
    'Sensory Disturbances, but Not Motor Disturbances, Induced by Sensorimotor Conflicts Are Increased in the Presence of Acute Pain',
    'The combined action of a passive exoskeleton and an EMG-controlled neuroprosthesis for upper limb stroke rehabilitation: First results of the RETRAINER project',
    'Multiday Evaluation of Techniques for EMG-Based Classification of Hand Motions',
    'A hybrid brain-machine interface based on EEG and EMG activity for the motor rehabilitation of stroke patients',
    'Development of a model osseo-magnetic link for intuitive rotational control of upper-limb prostheses',
    'Closed-loop control of spinal cord stimulation to restore hand function after paralysis',
    'Coordinative Motion-Based Bilateral Rehabilitation Training System with Exoskeleton and Haptic Devices for Biomedical Application',
    'FES-induced co-activation of antagonist muscles for upper limb control and disturbance rejection',
    'Reinforced feedback in virtual environment for rehabilitation of upper extremity dysfunction after stroke: preliminary data from a randomized controlled trial',
    'Two degrees of freedom quasi-static EMG-force at the wrist using a minimum number of electrodes',
    'Pattern recognition control outperforms conventional myoelectric control in upper limb patients with targeted muscle reinnervation',
    'Proceedings of the first workshop on Peripheral Machine Interfaces: going beyond traditional surface electromyography',
    'Hand Control With Invasive Feedback Is Not Impaired by Increased Cognitive Load',
    'Towards Efficient Decoding of Multiple Classes of Motor Imagery Limb Movements Based on EEG Spectral and Time Domain Descriptors',
    'Stroke participant\'s perceptions of robotic and electrical stimulation therapy: a new approach',
    'Long-term stability of sensitivity to intracortical microstimulation of somatosensory cortex',
    'Research on a novel artificial anal sphincter for human incontinence',
    'EMG-Based Continuous and Simultaneous Estimation of Arm Kinematics in Able-Bodied Individuals and Stroke Survivors',
    'Restoring motor control and sensory feedback in people with upper extremity amputations using arrays of 96 microelectrodes implanted in the median and ulnar nerves',
    'Transcranial direct current stimulation (tDCS) of the primary motor cortex and robot-assisted arm training in chronic incomplete cervical spinal cord injury: A proof of concept sham-randomized clinical study',
    'Spatial asymmetry in tactile sensor skin deformation aids perception of edge orientation during haptic exploration',
    'Clinical study of neurorehabilitation in stroke using EEG-based motor imagery brain-computer interface with robotic feedback',
    'Quantitative assessment of limb position sense following stroke',
    'Integrated vision-based robotic arm interface for operators with upper limb mobility impairments',
    'A cervical propriospinal system in man',
    'Gravity compensation of an upper extremity exoskeleton',
    'Proportional EMG control for upper-limb powered exoskeletons',
    'Design and Optimization of an EEG-Based Brain Machine Interface (BMI) to an Upper-Limb Exoskeleton for Stroke Survivors',
    'Consumer design priorities for upper limb prosthetics',
    'Sensory feedback control of upper- and lower-extremity motor prostheses',
    'An EMG-driven exoskeleton hand robotic training device on chronic stroke subjects: task training system for stroke rehabilitation',
    'Error amplification to promote motor learning and motivation in therapy robotics',
    'Body Segment Mechanical Signal Contributions to Continuous Prediction of Locomotor Transitions Performed under Varying Anticipation',
    'New control strategies for neuroprosthetic systems',
    'Proposal of bioinstrumentation using shape deformation of amputated upper limb',
    'Patient perspectives on benefits and risks of implantable interfaces for upper limb prostheses: a national survey',
    'Assistive control system using continuous myoelectric signal in robot-aided arm training for patients after stroke',
    'Experimental results using force-feedback cueing in robot-assisted stroke therapy',
    'Staying in Touch: Toward the Restoration of Sensory Feedback in Hand Prostheses Using Peripheral Neural Stimulation',
    'Advances in the use of electrical stimulation for the recovery of motor function',
    'Illusion of arm movement evoked by tendon vibration in patients with spinal cord injury',
    'Adaptive control of 5 DOF upper-limb exoskeleton robot with improved safety',
    'Biomechanical and neural changes evaluation induced by prolonged use of non-stable footwear: a systematic review',
    'Physically interactive robotic technology for neuromotor rehabilitation',
    'Wireless radio channel for intramuscular electrode implants in the control of upper limb prostheses',
    'Volitional walking via upper limb muscle-controlled stimulation of the lumbar locomotor center in man',
    'Innovative approaches to the rehabilitation of upper extremity hemiparesis using virtual environments',
    'An EMG-controlled neuroprosthesis for daily upper limb support: a preliminary study',
    'Two ways to improve myoelectric control for a transhumeral amputee after targeted muscle reinnervation: a case study',
    'Simulating the impact of sensorimotor deficits on reaching performance',
    'Moving sounds within the peripersonal space modulate the motor system',
    'Vibrotactile detection thresholds for chest skin of amputees following targeted reinnervation surgery',
    'Lesion locations associated with persistent proprioceptive impairment in the upper limbs after stroke',
    'Development and Feasibility Assessment of a Rotational Orthosis for Walking with Arm Swing',
    'A robotic & virtual reality orthopedic rehabilitation system for the forearm',
    'An advanced rehabilitation robotic system for augmenting healthcare',
    'Tri-state myoelectric control of bilateral upper extremity neuroprostheses for tetraplegic individuals',
    'sEMG-based joint force control for an upper-limb power-assist exoskeleton robot',
    'Prosthesis Control with an Implantable Multichannel Wireless Electromyography System for High-Level Amputees: A Large-Animal Study',
    'Channel selection for simultaneous and proportional myoelectric prosthesis control of multiple degrees-of-freedom',
    'Upper limb amputees can be induced to experience a rubber hand as their own',
    'First-in-man demonstration of a fully implanted myoelectric sensors system to control an advanced electromechanical prosthetic hand',
    'Representing high-dimensional data to intelligent prostheses and other wearable assistive robots: A first comparison of tile coding and selective Kanerva coding',
    'Stroke: posthospital management and recurrence prevention',
    'Kinematic and neurophysiological consequences of an assisted-force-feedback brain-machine interface training: a case study',
    'An affordable, computerised, table-based exercise system for stroke survivors',
    'High Cable Forces Deteriorate Pinch Force Control in Voluntary-Closing Body-Powered Prostheses',
    'Semi-Autonomous Robotic Arm Reaching With Hybrid Gaze-Brain Machine Interface',
    'Automating arm movement training following severe stroke: functional exercises with quantitative feedback in a gravity-reduced environment',
    'Temporal coding of brain patterns for direct limb control in humans',
    'Directional Forgetting for Stable Co-Adaptation in Myoelectric Control',
    'An identification technique for evaluating body segment parameters in the upper extremity from manipulator-hand contact forces and arm kinematics',
    'Upper extremity limb loss: functional restoration from prosthesis and targeted reinnervation to transplantation',
    'Combining two open source tools for neural computation (BioPatRec and Netlab) improves movement classification for prosthetic control',
    'Detecting the Intention to Move Upper Limbs from Electroencephalographic Brain Signals',
    'A neural interface provides long-term stable natural touch perception',
    'Towards brain-robot interfaces in stroke rehabilitation',
    'Promoting clinical best practice in a user-centred design study of an upper limb rehabilitation robot',
    'The use of a bone-anchored device as a hard-wired conduit for transmitting EMG signals from implanted muscle electrodes',
    'Targeted reinnervation for improved prosthetic function',
    'Spatio-temporal evaluation of neck muscle activation during postural perturbations in healthy subjects',
    'Learning a novel myoelectric-controlled interface task',
    'Quality parameters for a multimodal EEG/EMG/kinematic brain-computer interface (BCI) aiming to suppress neurological tremor in upper limbs',
    'Continuous motion decoding from EMG using independent component analysis and adaptive model training',
    'Upper limb joint angle tracking with inertial sensors',
    'Artificial kinesthetic systems for telerehabilitation',
    'Sensory capacity of reinnervated skin after redirection of amputated upper limb nerves to the chest',
    'Design and validation of a rehabilitation robotic exoskeleton for tremor assessment and suppression',
    'Proof of Concept of an Online EMG-Based Decoding of Hand Postures and Individual Digit Forces for Prosthetic Hand Control',
    'A proof of concept study investigating the feasibility of combining iPAM robot assisted rehabilitation with functional electrical stimulation to deliver whole arm exercise in stroke survivors',
    'Touch on predefined areas on the forearm can be associated with specific fingers: Towards a new principle for sensory feedback in hand prostheses',
    'User and clinician perspectives on DEKA arm: results of VA study to optimize DEKA arm',
    'Long-Term Home-Use of Sensory-Motor-Integrated Bidirectional Bionic Prosthetic Arms Promotes Functional, Perceptual, and Cognitive Changes',
    'Sensory feedback in a myoelectric upper limb prosthesis: a preliminary report',
    'Repeated Exposure to Forward Support-Surface Perturbation During Overground Walking Alters Upper-Body Kinematics and Step Parameters',
    'A novel robot device in rehabilitation of post-stroke hemiplegic upper limbs',
    'Multimodal BCI-mediated FES suppression of pathological tremor',
    'Prosthetic arm monitoring system using a programmable interface controller',
    'Broadband Prosthetic Interfaces: Combining Nerve Transfers and Implantable Multichannel EMG Technology to Decode Spinal Motor Neuron Activity',
    'Assessment of brain-machine interfaces from the perspective of people with paralysis',
    'Online human training of a myoelectric prosthesis controller via actor-critic reinforcement learning',
    'Preliminary results on the design of a tool for inserting of transverse intrafascicular multichannel electrodes (TIME) into the peripheral nervous system',
    'Mechanotactile Sensory Feedback Improves Embodiment of a Prosthetic Hand During Active Use',
    'Pilot study to test effectiveness of video game on reaching performance in stroke',
    'Web-based telerehabilitation for the upper extremity after stroke',
    'Effects of priming intermittent theta burst stimulation on upper limb motor recovery after stroke: study protocol for a proof-of-concept randomised controlled trial',
    'Design and control of RUPERT: a device for robotic upper extremity repetitive therapy',
    'Closed-Loop Neuroprosthesis for Reach-to-Grasp Assistance: Combining Adaptive Multi-channel Neuromuscular Stimulation with a Multi-joint Arm Exoskeleton',
    'Bio cooperative robotic platform for motor function recovery of the upper limb after stroke',
    'The eWrist - A wearable wrist exoskeleton with sEMG-based force control for stroke rehabilitation',
    'Evaluation of negative viscosity as upper extremity training for stroke survivors',
    'Lasting Effects of Low-Frequency Repetitive Transcranial Magnetic Stimulation in Writer\'s Cramp: A Case Report',
    'Cineplasty as a control input for externally powered prosthetic components',
    'Standard task set for evaluating rehabilitation interventions for individuals with arm paralysis',
    'A realistic implementation of ultrasound imaging as a human-machine interface for upper-limb amputees',
    'Haptic Error Modulation Outperforms Visual Error Amplification When Learning a Modified Gait Pattern',
    'Comfort and learnability assessment of a new soft robotic manipulator for minimally invasive surgery',
    'An implanted upper-extremity neuroprosthesis using myoelectric control',
    'Shoulder motion assistance using a single-joint Hybrid Assistive Limb Â® robot: Evaluation of its safety and validity in healthy adults',
    'Outcome instruments for prosthetics: clinical applications',
    'Robust tactile sensory responses in finger area of primate motor cortex relevant to prosthetic control',
    'Probability-based prediction of activity in multiple arm muscles: implications for functional electrical stimulation',
    'Virtual Reality for Sensorimotor Rehabilitation Post-Stroke: The Promise and Current State of the Field',
    'Improving Upper Extremity Function and Quality of Life with a Tongue Driven Exoskeleton: A Pilot Study Quantifying Stroke Rehabilitation',
    'Robot-assisted reaching exercise promotes arm movement recovery in chronic hemiparetic stroke: a randomized controlled pilot study',
    'Exploring teleimpedance and tactile feedback for intuitive control of the Pisa/IIT SoftHand',
    'Evoking Apparent Moving Sensation in the Hand via Transcutaneous Electrical Nerve Stimulation',
    'Building blocks system for a prosthesis training of a child with congenital amputee',
    'Estimating the patient\'s contribution during robot-assisted therapy',
    'Spatial correlation of high density EMG signals provides features robust to electrode number and shift in pattern recognition for myocontrol',
    'Design of a rotational hydroelastic actuator for a powered exoskeleton for upper limb rehabilitation',
    'Estimation of continuous elbow joint movement based on human physiological structure',
    'Towards the control of individual fingers of a prosthetic hand using surface EMG signals',
    'Novel Method for Predicting Dexterous Individual Finger Movements by Imaging Muscle Activity Using a Wearable Ultrasonic System',
    'An EMG-based robot control scheme robust to time-varying EMG signal features',
    'Novel targeted sensory reinnervation technique to restore functional hand sensation after transhumeral amputation',
    'Simultaneous and proportional force estimation for multifunction myoelectric prostheses using mirrored bilateral training',
    'Clinical implications of using the arm motor ability test in stroke rehabilitation',
    'Feasibility of using combined EMG and kinematic signals for prosthesis control: A simulation study using a virtual reality environment',
    'Incorporating haptic effects into three-dimensional virtual environments to train the hemiparetic upper extremity',
    'Asynchronous steady-state visual evoked potential based BCI control of a 2-DoF artificial upper limb',
    'Neurorehabilitation of upper extremities in humans with sensory-motor impairment',
    'Subcutaneous abdominal artificial tears pump-reservoir for severe dry eye',
    'Closed-Loop Task Difficulty Adaptation during Virtual Reality Reach-to-Grasp Training Assisted with an Exoskeleton for Stroke Rehabilitation',
    'A novel approach to stroke rehabilitation: robot-aided sensorimotor stimulation',
    'Efficacy and stability performance of traditional versus motion sensor-assisted strategies for FES standing',
    'Wrist action affects precision grip force',
    'Raised corticomotor excitability of M1 forearm area following anodal tDCS is sustained during robotic wrist therapy in chronic stroke',
    'Learning to use a body-powered prosthesis: changes in functionality and kinematics',
    'Real-time and offline performance of pattern recognition myoelectric control using a generic electrode grid with targeted muscle reinnervation patients',
    'The effects of electromechanical wrist robot assistive system with neuromuscular electrical stimulation for stroke rehabilitation',
    'Linear and nonlinear regression techniques for simultaneous and proportional myoelectric control',
    'Sensitivity and specificity of upper extremity movements decoded from electrocorticogram',
    'Differentiating Variations in Thumb Position From Recordings of the Surface Electromyogram in Adults Performing Static Grips, a Proof of Concept Study',
    'Human body contour data based activity recognition',
    'The influence of electrode position on bipolar surface electromyogram recordings of the upper trapezius muscle',
    'RUPERT: a Device for Robotic Upper Extremity Repetitive Therapy',
    'Error-enhancing robot therapy to induce motor control improvement in childhood onset primary dystonia',
    'The influence of artificially increased hip and trunk stiffness on balance control in man',
    'User ratings of prosthetic usability and satisfaction in VA study to optimize DEKA arm',
    'Development and feasibility study of a sensory-enhanced robot-aided motor training in stroke rehabilitation',
    'Normalized movement quality measures for therapeutic robots strongly correlate with clinical motor impairment measures',
    'Temporal Asynchrony but Not Total Energy Nor Duration Improves the Judgment of Numerosity in Electrotactile Stimulation',
    'A Method of Recognizing Finger Motion Using Wavelet Transform of Surface EMG Signal',
    'Design strategies to improve patient motivation during robot-aided rehabilitation',
    'Physiological and behavioral effects of Î²-tACS on brain self-regulation in chronic stroke',
    'Identification of Upper-Limb Movements Based on Muscle Shape Change Signals for Human-Robot Interaction',
    'Shoulder and forearm oxygenation and myoelectric activity in patients with work-related muscle pain and healthy subjects',
    'A novel rehabilitation system for upper limbs',
    'Learning, Generalization, and Scalability of Abstract Myoelectric Control',
    'A learning scheme for reach to grasp movements: on EMG-based interfaces using task specific motion decoding models',
    'Rehabilitation of the Upper Extremity after Stroke: A Case Series Evaluating REO Therapy and an Auditory Sensor Feedback for Trunk Control',
    'Continuous myoelectric control for powered prostheses using hidden Markov models',
    'An unusual complication of a myoelectric prosthesis',
    'A concept for extending the applicability of constraint-induced movement therapy through motor cortex activity feedback using a neural prosthesis',
    'Use of a Behavioural Pain Scale to assess pain in ventilated, unconscious and/or sedated patients',
    'New technologies and concepts for rehabilitation in the acute phase of stroke: a collaborative matrix',
    'Electrically evoked myoelectric signals in back muscles: effect of side dominance',
    'Hand Extension Robot Orthosis (HERO) Grip Glove: enabling independence amongst persons with severe hand impairments after stroke',
    'A control system for a powered prosthesis using positional and myoelectric inputs from the shoulder complex',
    'Integrating proprioceptive assessment with proprioceptive training of stroke patients',
    'Feasibility of EMG-based neural network controller for an upper extremity neuroprosthesis',
    'Standardising surface electromyogram recordings for assessment of activity and fatigue in the human upper trapezius muscle',
    'Development of a haptic interface for motor rehabilitation therapy using augmented reality',
    'Electroactive polymeric sensors in hand prostheses: bending response of an ionic polymer metal composite',
    'Robot-assisted therapy for neuromuscular training of sub-acute stroke patients. A feasibility study',
    'Error augmentation enhancing arm recovery in individuals with chronic stroke: a randomized crossover design',
    'Shoulder abduction-induced reductions in reaching work area following hemiparetic stroke: neuroscientific implications',
    'The Conventional Non-Articulated SACH or a Multiaxial Prosthetic Foot for Hypomobile Transtibial Amputees? A Clinical Comparison on Mobility, Balance, and Quality of Life',
    'Effect of platelet-derived growth factor isoforms on the migration of mouse embryo limb myogenic cells',
    'Respiratory-dependent pacing: a dual response from a single sensor',
    'The effect of head position, electrode site, movement and smoothing window in the determination of a reliable maximum voluntary activation of the upper trapezius muscle',
    'A multifunctional prosthesis control system based on time series identification of EMG signals using microprocessors',
    'Functional restoration of elbow extension after spinal-cord injury using a neural network-based synergistic FES controller',
    'Predicting targets of human reaching motions using different sensing technologies',
    'Wearable Dual-Frequency Vibrotactile System for Restoring Force and Stiffness Perception',
    'Estimation of the knee joint angle from surface electromyographic signals for active control of leg prostheses',
    'Orthotopic and heterotopic lower leg reimplantation. Evaluation of seven patients',
    'Estimation of continuous multi-DOF finger joint kinematics from surface EMG using a multi-output Gaussian Process',
    'Evaluation of a wearable orthosis and an associated algorithm for tremor suppression',
    'A miniature vibrotactile sensory substitution device for multifingered hand prosthetics',
    'Qualitative evaluation of the masseteric poststimulus EMG complex following mechanical or acoustic stimulation of osseointegrated oral implants',
    'Motion recognition for simultaneous control of multifunctional transradial prostheses',
    'Control of a pneumatic orthosis for upper extremity stroke rehabilitation',
    'A comparison between control methods for implanted FES hand-grasp systems',
    'A proof of concept study for the integration of robot therapy with physiotherapy in the treatment of stroke patients',
    'Simulation of variable impedance as an intervention for upper extremity motor exploration',
    'High density electromyography data of normally limbed and transradial amputee subjects for multifunction prosthetic control',
    'Targeted muscle reinnervation of a muscle-free flap for improved prosthetic control in a shoulder amputee: case report',
    'Regulation of multijoint stretch reflexes during interactions with stiff and compliant environments',
    'Robotics-assisted visual-motor training influences arm position sense in three-dimensional space',
    'Bilateral transfer in active and passive guidance-reproduction based bimanual tasks: effect of proprioception and handedness',
    'Congenital hypomyelination neuropathy in a newborn infant: unusual cause of diaphragmatic and vocal cord paralyses',
    'A robust, real-time control scheme for multifunction myoelectric control',
    'Real-time haptic-teleoperated robotic system for motor control analysis',
    'Leg length preservation with pedicled fillet of foot flaps after traumatic amputations',
    'A model of the upper extremity using FES for stroke rehabilitation',
    'Arm control recovery enhanced by error augmentation',
    'A state-based, proportional myoelectric control method: online validation and comparison with the clinical state-of-the-art',
    'Real-time myoprocessors for a neural controlled powered exoskeleton arm',
    'Design and development of a hand robotic rehabilitation device for post stroke patients',
    'An analysis of extended physiological proprioception as a prosthesis-control technique',
    'Towards control of dexterous hand manipulations using a silicon Pattern Generator',
    'A comparison of alternative means of providing sensory feedback on upper limb prostheses',
    'The relationships between movement-related cortical potentials and motor unit activity during muscle contraction',
    'Bayesian State Estimation in Sensorimotor Systems With Particle Filtering',
    'Clinical detection and movement recognition of neuro signals',
    '[Effects of intravenous electrodes of cardiac pacemakers. Clinical and plethysmographic approach]',
    '[Treatment of an orbital defect with an eye prosthesis with an electronically controlled eyelid, synchronous to the intact eye]',
    'Hand motion recognition based on forearm deformation measured with a distance sensor array',
    'Decoding bipedal locomotion from the rat sensorimotor cortex',
    'Neural control of on-line guidance of hand reaching movements',
    'Non-invasive treatment of patients with upper extremity spasticity following stroke using paired trans-spinal and peripheral direct current stimulation',
    'Command of an upper extremity FES system using a simple set of commands',
    'Counteracting Electrode Shifts in Upper-Limb Prosthesis Control via Transfer Learning',
    'Systematic Review on Kinematic Assessments of Upper Limb Movements After Stroke',
    'A Novel Time-Domain Descriptor for Improved Prediction of Upper Limb Movement Intent in EMG-PR System',
    'Implantation of SphinKeeper(TM): a new artificial anal sphincter',
    'Neuromuscular stimulation after stroke: from technology to clinical deployment',
    'Continuous Estimation of Human Multi-Joint Angles From sEMG Using a State-Space Model',
    'Noninvasive assessment of cardiac output by brachial occlusion-cuff technique: comparison with the open-circuit acetylene washin method',
    'Electrically stimulated signals from a long-term Regenerative Peripheral Nerve Interface',
    'Simultaneous, proportional, multi-axis prosthesis control using multichannel surface EMG',
    'Development of an EMG-Based Muscle Health Model for Elbow Trauma Patients',
    'Classification of simultaneous movements using surface EMG pattern recognition',
    'Advances in selective activation of muscles for non-invasive motor neuroprostheses',
    '[Study on the method of microelectrodes implantation of artificial facial nerve prosthesis in closed mouth of orbicularis oris muscle in monkeys with facial nerve paralysis]',
    'Muscle length and joint angle influence spinal but not corticospinal excitability to the biceps brachii across forearm postures'
  ];
  void _addToCollection() {
    Map<String, dynamic> newDocument;
    for (int i = 0; i < _paperTitles.length; ++i) {
      newDocument = {'Maybe': 0, 'No': 0, 'Title': _paperTitles[i], 'Yes': 0};
      Firestore.instance.collection('paper_titles').add(newDocument);
    }
  }

  void setContext(BuildContext context) => _context = context;
  int getCurrentPaperIndex() => _paperIndex;
  int setCurrentPaperIndex(int index) => _paperIndex = index;
  int getNumPapers() => _paperTitles.length;
  String getCurrentPaperTitle() => _paperTitles[_paperIndex];
  bool getNextPaper() {
    if (_paperIndex < _paperTitles.length - 1) {
      ++_paperIndex;
      return true;
    }
    Alert(
            context: _context,
            title: "Out of Papers",
            desc: "Have Checked All Papers")
        .show();
    return false;
  }

  bool getPreviousPaper() {
    if (_paperIndex > 0) {
      --_paperIndex;
      return true;
    }
    Alert(context: _context, title: "First Paper", desc: "Back to the start!")
        .show();
    return false;
  }
}
